# Copyright © 2023 the MEP-OAI Authors

# Licensed under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License. 
# API Version: 0.0.1
# Contact: netsoft@eurecom.fr

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oai_rnis.models.base_model_ import Model
from oai_rnis.models.link_type import LinkType  # noqa: F401,E501
from oai_rnis.utils import util


class CaReconfSubscriptionLinks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _self: LinkType=None):  # noqa: E501
        """CaReconfSubscriptionLinks - a model defined in Swagger

        :param _self: The _self of this CaReconfSubscriptionLinks.  # noqa: E501
        :type _self: LinkType
        """
        self.swagger_types = {
            '_self': LinkType
        }

        self.attribute_map = {
            '_self': 'self'
        }
        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'CaReconfSubscriptionLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CaReconfSubscription__links of this CaReconfSubscriptionLinks.  # noqa: E501
        :rtype: CaReconfSubscriptionLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> LinkType:
        """Gets the _self of this CaReconfSubscriptionLinks.


        :return: The _self of this CaReconfSubscriptionLinks.
        :rtype: LinkType
        """
        return self.__self

    @_self.setter
    def _self(self, _self: LinkType):
        """Sets the _self of this CaReconfSubscriptionLinks.


        :param _self: The _self of this CaReconfSubscriptionLinks.
        :type _self: LinkType
        """
        if _self is None:
            raise ValueError("Invalid value for `_self`, must not be `None`")  # noqa: E501

        self.__self = _self
