# Copyright © 2023 the MEP-OAI Authors

# Licensed under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License. 
# API Version: 0.0.1
# Contact: netsoft@eurecom.fr

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oai_rnis.models.base_model_ import Model
from oai_rnis.utils import util


class ExpiryNotificationLinks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _self: str=None):  # noqa: E501
        """ExpiryNotificationLinks - a model defined in Swagger

        :param _self: The _self of this ExpiryNotificationLinks.  # noqa: E501
        :type _self: str
        """
        self.swagger_types = {
            '_self': str
        }

        self.attribute_map = {
            '_self': 'self'
        }
        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'ExpiryNotificationLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExpiryNotification__links of this ExpiryNotificationLinks.  # noqa: E501
        :rtype: ExpiryNotificationLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> str:
        """Gets the _self of this ExpiryNotificationLinks.

        Self referring URI. This shall be included in the response from the RNIS. The URI shall be unique within the RNI API as it acts as an ID for the subscription.  # noqa: E501

        :return: The _self of this ExpiryNotificationLinks.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self: str):
        """Sets the _self of this ExpiryNotificationLinks.

        Self referring URI. This shall be included in the response from the RNIS. The URI shall be unique within the RNI API as it acts as an ID for the subscription.  # noqa: E501

        :param _self: The _self of this ExpiryNotificationLinks.
        :type _self: str
        """
        if _self is None:
            raise ValueError("Invalid value for `_self`, must not be `None`")  # noqa: E501

        self.__self = _self
