# Copyright © 2023 the MEP-OAI Authors

# Licensed under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License. 
# API Version: 0.0.1
# Contact: netsoft@eurecom.fr

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oai_rnis.models.base_model_ import Model
from oai_rnis.utils import util


class LinkType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, href: str=None):  # noqa: E501
        """LinkType - a model defined in Swagger

        :param href: The href of this LinkType.  # noqa: E501
        :type href: str
        """
        self.swagger_types = {
            'href': str
        }

        self.attribute_map = {
            'href': 'href'
        }
        self._href = href

    @classmethod
    def from_dict(cls, dikt) -> 'LinkType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinkType of this LinkType.  # noqa: E501
        :rtype: LinkType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def href(self) -> str:
        """Gets the href of this LinkType.

        URI referring to a resource  # noqa: E501

        :return: The href of this LinkType.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this LinkType.

        URI referring to a resource  # noqa: E501

        :param href: The href of this LinkType.
        :type href: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href
