# Copyright © 2023 the OAI-RNIS Authors

# Licensed under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License. 
# Contact: netsoft@eurecom.fr

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oai_rnis.models.base_model_ import Model
from oai_rnis.models.ng_bearer_info_ng_ue_info import NGBearerInfoNgUeInfo  # noqa: F401,E501
from oai_rnis.models.time_stamp import TimeStamp  # noqa: F401,E501
from oai_rnis.utils import util


class NGBearerInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ng_ue_info: List[NGBearerInfoNgUeInfo]=None, time_stamp: TimeStamp=None):  # noqa: E501
        """NGBearerInfo - a model defined in Swagger

        :param ng_ue_info: The ng_ue_info of this NGBearerInfo.  # noqa: E501
        :type ng_ue_info: List[NGBearerInfoNgUeInfo]
        :param time_stamp: The time_stamp of this NGBearerInfo.  # noqa: E501
        :type time_stamp: TimeStamp
        """
        self.swagger_types = {
            'ng_ue_info': List[NGBearerInfoNgUeInfo],
            'time_stamp': TimeStamp
        }

        self.attribute_map = {
            'ng_ue_info': 'ngUeInfo',
            'time_stamp': 'timeStamp'
        }
        self._ng_ue_info = ng_ue_info
        self._time_stamp = time_stamp

    @classmethod
    def from_dict(cls, dikt) -> 'NGBearerInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NGBearerInfo of this NGBearerInfo.  # noqa: E501
        :rtype: NGBearerInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ng_ue_info(self) -> List[NGBearerInfoNgUeInfo]:
        """Gets the ng_ue_info of this NGBearerInfo.

        Information on a specific UE as defined below.  # noqa: E501

        :return: The ng_ue_info of this NGBearerInfo.
        :rtype: List[NGBearerInfoNgUeInfo]
        """
        return self._ng_ue_info

    @ng_ue_info.setter
    def ng_ue_info(self, ng_ue_info: List[NGBearerInfoNgUeInfo]):
        """Sets the ng_ue_info of this NGBearerInfo.

        Information on a specific UE as defined below.  # noqa: E501

        :param ng_ue_info: The ng_ue_info of this NGBearerInfo.
        :type ng_ue_info: List[NGBearerInfoNgUeInfo]
        """
        if ng_ue_info is None:
            raise ValueError("Invalid value for `ng_ue_info`, must not be `None`")  # noqa: E501

        self._ng_ue_info = ng_ue_info

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this NGBearerInfo.


        :return: The time_stamp of this NGBearerInfo.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this NGBearerInfo.


        :param time_stamp: The time_stamp of this NGBearerInfo.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp
