# Copyright © 2023 the OAI-RNIS Authors

# Licensed under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License. 
# Contact: netsoft@eurecom.fr

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oai_rnis.models.base_model_ import Model
from oai_rnis.models.ca_reconf_subscription_links import CaReconfSubscriptionLinks  # noqa: F401,E501
from oai_rnis.models.enum import Enum  # noqa: F401,E501
from oai_rnis.models.ng_bearer_subscription_ng_bearer_subscription_criteria import NGBearerSubscriptionNGBearerSubscriptionCriteria  # noqa: F401,E501
from oai_rnis.models.time_stamp import TimeStamp  # noqa: F401,E501
from oai_rnis.utils import util


class NGBearerSubscription(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ng_bearer_subscription_criteria: NGBearerSubscriptionNGBearerSubscriptionCriteria=None, links: CaReconfSubscriptionLinks=None, callback_reference: str=None, event_type: List[Enum]=None, expiry_deadline: TimeStamp=None, subscription_type: str=None):  # noqa: E501
        """NGBearerSubscription - a model defined in Swagger

        :param ng_bearer_subscription_criteria: The ng_bearer_subscription_criteria of this NGBearerSubscription.  # noqa: E501
        :type ng_bearer_subscription_criteria: NGBearerSubscriptionNGBearerSubscriptionCriteria
        :param links: The links of this NGBearerSubscription.  # noqa: E501
        :type links: CaReconfSubscriptionLinks
        :param callback_reference: The callback_reference of this NGBearerSubscription.  # noqa: E501
        :type callback_reference: str
        :param event_type: The event_type of this NGBearerSubscription.  # noqa: E501
        :type event_type: List[Enum]
        :param expiry_deadline: The expiry_deadline of this NGBearerSubscription.  # noqa: E501
        :type expiry_deadline: TimeStamp
        :param subscription_type: The subscription_type of this NGBearerSubscription.  # noqa: E501
        :type subscription_type: str
        """
        self.swagger_types = {
            'ng_bearer_subscription_criteria': NGBearerSubscriptionNGBearerSubscriptionCriteria,
            'links': CaReconfSubscriptionLinks,
            'callback_reference': str,
            'event_type': List[Enum],
            'expiry_deadline': TimeStamp,
            'subscription_type': str
        }

        self.attribute_map = {
            'ng_bearer_subscription_criteria': 'NGBearerSubscriptionCriteria',
            'links': '_links',
            'callback_reference': 'callbackReference',
            'event_type': 'eventType',
            'expiry_deadline': 'expiryDeadline',
            'subscription_type': 'subscriptionType'
        }
        self._ng_bearer_subscription_criteria = ng_bearer_subscription_criteria
        self._links = links
        self._callback_reference = callback_reference
        self._event_type = event_type
        self._expiry_deadline = expiry_deadline
        self._subscription_type = subscription_type

    @classmethod
    def from_dict(cls, dikt) -> 'NGBearerSubscription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NGBearerSubscription of this NGBearerSubscription.  # noqa: E501
        :rtype: NGBearerSubscription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ng_bearer_subscription_criteria(self) -> NGBearerSubscriptionNGBearerSubscriptionCriteria:
        """Gets the ng_bearer_subscription_criteria of this NGBearerSubscription.


        :return: The ng_bearer_subscription_criteria of this NGBearerSubscription.
        :rtype: NGBearerSubscriptionNGBearerSubscriptionCriteria
        """
        return self._ng_bearer_subscription_criteria

    @ng_bearer_subscription_criteria.setter
    def ng_bearer_subscription_criteria(self, ng_bearer_subscription_criteria: NGBearerSubscriptionNGBearerSubscriptionCriteria):
        """Sets the ng_bearer_subscription_criteria of this NGBearerSubscription.


        :param ng_bearer_subscription_criteria: The ng_bearer_subscription_criteria of this NGBearerSubscription.
        :type ng_bearer_subscription_criteria: NGBearerSubscriptionNGBearerSubscriptionCriteria
        """
        if ng_bearer_subscription_criteria is None:
            raise ValueError("Invalid value for `ng_bearer_subscription_criteria`, must not be `None`")  # noqa: E501

        self._ng_bearer_subscription_criteria = ng_bearer_subscription_criteria

    @property
    def links(self) -> CaReconfSubscriptionLinks:
        """Gets the links of this NGBearerSubscription.


        :return: The links of this NGBearerSubscription.
        :rtype: CaReconfSubscriptionLinks
        """
        return self._links

    @links.setter
    def links(self, links: CaReconfSubscriptionLinks):
        """Sets the links of this NGBearerSubscription.


        :param links: The links of this NGBearerSubscription.
        :type links: CaReconfSubscriptionLinks
        """

        self._links = links

    @property
    def callback_reference(self) -> str:
        """Gets the callback_reference of this NGBearerSubscription.

        URI selected by the service consumer, to receive notifications on the subscribed RNIS information. This shall be included in the request and response.  # noqa: E501

        :return: The callback_reference of this NGBearerSubscription.
        :rtype: str
        """
        return self._callback_reference

    @callback_reference.setter
    def callback_reference(self, callback_reference: str):
        """Sets the callback_reference of this NGBearerSubscription.

        URI selected by the service consumer, to receive notifications on the subscribed RNIS information. This shall be included in the request and response.  # noqa: E501

        :param callback_reference: The callback_reference of this NGBearerSubscription.
        :type callback_reference: str
        """
        if callback_reference is None:
            raise ValueError("Invalid value for `callback_reference`, must not be `None`")  # noqa: E501

        self._callback_reference = callback_reference

    @property
    def event_type(self) -> List[Enum]:
        """Gets the event_type of this NGBearerSubscription.

        Description of the subscribed event. The event is included both in the request and in the response. \\nFor the eventType, the following values are currently defined: <p>0 = RESERVED. <p>1 = NG_BEARER_ESTABLISH. <p>2 = NG_BEARER_MODIFY. <p>3 = NG_BEARER_RELEASE.  # noqa: E501

        :return: The event_type of this NGBearerSubscription.
        :rtype: List[Enum]
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type: List[Enum]):
        """Sets the event_type of this NGBearerSubscription.

        Description of the subscribed event. The event is included both in the request and in the response. \\nFor the eventType, the following values are currently defined: <p>0 = RESERVED. <p>1 = NG_BEARER_ESTABLISH. <p>2 = NG_BEARER_MODIFY. <p>3 = NG_BEARER_RELEASE.  # noqa: E501

        :param event_type: The event_type of this NGBearerSubscription.
        :type event_type: List[Enum]
        """
        if event_type is None:
            raise ValueError("Invalid value for `event_type`, must not be `None`")  # noqa: E501

        self._event_type = event_type

    @property
    def expiry_deadline(self) -> TimeStamp:
        """Gets the expiry_deadline of this NGBearerSubscription.


        :return: The expiry_deadline of this NGBearerSubscription.
        :rtype: TimeStamp
        """
        return self._expiry_deadline

    @expiry_deadline.setter
    def expiry_deadline(self, expiry_deadline: TimeStamp):
        """Sets the expiry_deadline of this NGBearerSubscription.


        :param expiry_deadline: The expiry_deadline of this NGBearerSubscription.
        :type expiry_deadline: TimeStamp
        """

        self._expiry_deadline = expiry_deadline

    @property
    def subscription_type(self) -> str:
        """Gets the subscription_type of this NGBearerSubscription.

        Shall be set to \"NGBearerSubscription\".  # noqa: E501

        :return: The subscription_type of this NGBearerSubscription.
        :rtype: str
        """
        return self._subscription_type

    @subscription_type.setter
    def subscription_type(self, subscription_type: str):
        """Sets the subscription_type of this NGBearerSubscription.

        Shall be set to \"NGBearerSubscription\".  # noqa: E501

        :param subscription_type: The subscription_type of this NGBearerSubscription.
        :type subscription_type: str
        """
        if subscription_type is None:
            raise ValueError("Invalid value for `subscription_type`, must not be `None`")  # noqa: E501

        self._subscription_type = subscription_type
