# Copyright © 2023 the OAI-RNIS Authors

# Licensed under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License. 
# Contact: netsoft@eurecom.fr

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oai_rnis.models.base_model_ import Model
from oai_rnis.models.ng_bearer_info_enb_info import NGBearerInfoEnbInfo  # noqa: F401,E501
from oai_rnis.models.ng_bearer_info_s_gw_info import NGBearerInfoSGwInfo  # noqa: F401,E501
from oai_rnis.utils import util


class NGBearerInfoNgBearerInfoDetailed(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, enb_info: NGBearerInfoEnbInfo=None, erab_id: int=None, s_gw_info: NGBearerInfoSGwInfo=None):  # noqa: E501
        """NGBearerInfoNgBearerInfoDetailed - a model defined in Swagger

        :param enb_info: The enb_info of this NGBearerInfoNgBearerInfoDetailed.  # noqa: E501
        :type enb_info: NGBearerInfoEnbInfo
        :param erab_id: The erab_id of this NGBearerInfoNgBearerInfoDetailed.  # noqa: E501
        :type erab_id: int
        :param s_gw_info: The s_gw_info of this NGBearerInfoNgBearerInfoDetailed.  # noqa: E501
        :type s_gw_info: NGBearerInfoSGwInfo
        """
        self.swagger_types = {
            'enb_info': NGBearerInfoEnbInfo,
            'erab_id': int,
            's_gw_info': NGBearerInfoSGwInfo
        }

        self.attribute_map = {
            'enb_info': 'enbInfo',
            'erab_id': 'erabId',
            's_gw_info': 'sGwInfo'
        }
        self._enb_info = enb_info
        self._erab_id = erab_id
        self._s_gw_info = s_gw_info

    @classmethod
    def from_dict(cls, dikt) -> 'NGBearerInfoNgBearerInfoDetailed':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NGBearerInfo_ngBearerInfoDetailed of this NGBearerInfoNgBearerInfoDetailed.  # noqa: E501
        :rtype: NGBearerInfoNgBearerInfoDetailed
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enb_info(self) -> NGBearerInfoEnbInfo:
        """Gets the enb_info of this NGBearerInfoNgBearerInfoDetailed.


        :return: The enb_info of this NGBearerInfoNgBearerInfoDetailed.
        :rtype: NGBearerInfoEnbInfo
        """
        return self._enb_info

    @enb_info.setter
    def enb_info(self, enb_info: NGBearerInfoEnbInfo):
        """Sets the enb_info of this NGBearerInfoNgBearerInfoDetailed.


        :param enb_info: The enb_info of this NGBearerInfoNgBearerInfoDetailed.
        :type enb_info: NGBearerInfoEnbInfo
        """

        self._enb_info = enb_info

    @property
    def erab_id(self) -> int:
        """Gets the erab_id of this NGBearerInfoNgBearerInfoDetailed.

        The attribute that uniquely identifies a NG bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :return: The erab_id of this NGBearerInfoNgBearerInfoDetailed.
        :rtype: int
        """
        return self._erab_id

    @erab_id.setter
    def erab_id(self, erab_id: int):
        """Sets the erab_id of this NGBearerInfoNgBearerInfoDetailed.

        The attribute that uniquely identifies a NG bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :param erab_id: The erab_id of this NGBearerInfoNgBearerInfoDetailed.
        :type erab_id: int
        """

        self._erab_id = erab_id

    @property
    def s_gw_info(self) -> NGBearerInfoSGwInfo:
        """Gets the s_gw_info of this NGBearerInfoNgBearerInfoDetailed.


        :return: The s_gw_info of this NGBearerInfoNgBearerInfoDetailed.
        :rtype: NGBearerInfoSGwInfo
        """
        return self._s_gw_info

    @s_gw_info.setter
    def s_gw_info(self, s_gw_info: NGBearerInfoSGwInfo):
        """Sets the s_gw_info of this NGBearerInfoNgBearerInfoDetailed.


        :param s_gw_info: The s_gw_info of this NGBearerInfoNgBearerInfoDetailed.
        :type s_gw_info: NGBearerInfoSGwInfo
        """

        self._s_gw_info = s_gw_info
