#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
# BUILDER IMAGE
#    Valid for UBUNTU 18.04
#---------------------------------------------------------------------

FROM ubuntu:bionic AS flexric-build
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
 
#install developers pkg/repo
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
       build-essential \
       psmisc \
       git \
       gpg \
       wget \
       libsctp-dev \
       python3.8 \
       python3-dev \
       python3-pip \
       autotools-dev \
       automake \
       bison \
       libpcre2-dev \
       flex \
       ninja-build && \
       apt-get autoremove -y

# Install cmake 3.15 for swig build 
RUN wget -O cmake.sh https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.sh && sh ./cmake.sh --prefix=/usr/local --skip-license

RUN git clone https://github.com/swig/swig.git && \
    cd swig && \
    ./autogen.sh && \
    ./configure --prefix=/usr/ && \
    make && \
    make install

RUN git clone https://gitlab.eurecom.fr/mosaic5g/flexric.git && \
    cd flexric && \
    git checkout v1.0.0 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install 

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------

FROM ubuntu:bionic AS oai-flexric
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
 
#install developers pkg/repo
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
       psmisc \
       gpg \
       wget \
       libsctp-dev \
       python3.8 \
       python3-pip && \
       apt-get autoremove -y && \
       pip3 install pika

WORKDIR /usr/lib/x86_64-linux-gnu/

COPY --from=flexric-build \
    /usr/lib/x86_64-linux-gnu/libsctp.so.1 \
    /lib/x86_64-linux-gnu/libdl.so.2 \
    /lib/x86_64-linux-gnu/libpthread.so.0 \
    /lib/x86_64-linux-gnu/libc.so.6 \
    /lib64/ld-linux-x86-64.so.2 \
    /usr/local/lib/

COPY --from=flexric-build \
    /usr/local/lib/flexric/libmac_sm.so \
    /usr/local/lib/flexric/libkpm_sm.so \
    /usr/local/lib/flexric/librlc_sm.so \
    /usr/local/lib/flexric/libslice_sm.so \
    /usr/local/lib/flexric/libtc_sm.so \
    /usr/local/lib/flexric/libgtp_sm.so \
    /usr/local/lib/flexric/


WORKDIR /flexric/build/examples/xApp/python3/

COPY config.ini rnisxapp.py /flexric/build/examples/xApp/python3/

COPY --from=flexric-build \
    /flexric/build/src/xApp/libe42_xapp_shared.so \
    /flexric/build/src/xApp/

COPY --from=flexric-build \
    /flexric/build/examples/xApp/python3/ .

COPY --from=flexric-build \
    /flexric/build/examples/ric/nearRT-RIC /usr/local/bin/nearRT-RIC

EXPOSE 36421/sctp
EXPOSE 36422/sctp