apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: labns
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "slice1-vlan" }, { "name": "slice2-vlan" }]'
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'sleep 3600']
    stdin: true
    tty: true