apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: slice1-vlan
  namespace: labns
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "mode": "bridge",
    "master": "eth0",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "192.168.10.100/24",
          "gateway": "192.168.10.1"
        }
      ]
    }
  }'